package ProgramDocumentary;

public class ProgramDocumentary {
/**
 * Customer Table 
 * ---------------
 */
/*
	CREATE TABLE CUSTOMER (
    CUSTOMERUSERNAME VARCHAR2(10) PRIMARY KEY,
    CUSTOMERPASSWORD VARCHAR2(10) NOT NULL,
    FIRSTNAME VARCHAR2(15) NOT NULL,
    LASTNAME VARCHAR2(15) NOT NULL,
    DATEOFBIRTH DATE NOT NULL,
    GENDER VARCHAR2(7) NOT NULL,
    ADDRESS VARCHAR2(15),
    EMAILID VARCHAR2(25) NOT NULL,
    PHONENUMBER NUMBER(12) NOT NULL
	);
 */
/** 
 * Admin Table
 * --------------- 
 */
/*
    CREATE TABLE Admin (
    ADMINUSERNAME VARCHAR2(10) PRIMARY KEY,
    ADMINPASSWORD VARCHAR2(10) NOT NULL,
    FIRSTNAME VARCHAR2(15) NOT NULL,
    LASTNAME VARCHAR2(15) NOT NULL,
    DATEOFBIRTH DATE NOT NULL,
    GENDER VARCHAR2(7) NOT NULL,
    ADDRESS VARCHAR2(15),
    EMAILID VARCHAR2(25) NOT NULL,
    PHONENUMBER NUMBER(12) NOT NULL,
    );
 */
/** 
 * CarDetails Table
 * ----------------- 
 */
/*
 	CREATE TABLE CarDetails (
    CAR_NUMBER VARCHAR(15) PRIMARY KEY,
    BRAND VARCHAR(15),
    MODEL VARCHAR(15),
    CAR_PRICEDAY DECIMAL(10, 2),
    LOCATION VARCHAR(15),
    AVAILABLE NUMBER(1),
    ADMINUSERNAME VARCHAR2(15)
	);
 */
/** 
 * CarBillDetails Table
 * -------------------
 */
	
/*
 *CREATE TABLE CARRENTEDBILL (
    ORDERBILL VARCHAR(15) PRIMARY KEY,
    CUSTOMERUSERID VARCHAR(10),
    CUSTOMERNAME VARCHAR(15),
    CUSTOMERMOBILENUMBER NUMBER(15),
    CUSTOMEREMAILID VARCHAR(25),
    CARBRAND VARCHAR(15),
    CARMODEL VARCHAR(15),
    CARNUMBER VARCHAR(15),
    JOURNEYSTARTDATE DATE,
    JOURNEYENDDATE DATE,
    TOTALDAYS NUMBER(3),
    RENTEDSTATUS VARCHAR(20),
    TOTALBILL NUMBER(10,2),
    ADMINID VARCHAR(15)
);

 */
	
}
